import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: {
    height: 56,
    backgroundColor: '#023c69',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  headerText: {
    color: '#fff',
    fontSize: 22,
    fontWeight: 'bold',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  mapContainer: {
    height: '50%',
    minHeight: 220,
    maxHeight: 400,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    overflow: 'hidden',
    backgroundColor: '#e6eaf0',
    elevation: 2,
    marginBottom: 8,
  },
  markerContainer: { alignItems: 'center' },
  priceTag: {
    backgroundColor: 'transparent',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#eee',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    alignItems: 'center',
    minWidth: 160,
  },
  priceText: { fontWeight: 'bold', color: '#222', fontSize: 16, textAlign: 'center' },
  addressText: {
    color: '#555',
    fontSize: 13,
    marginTop: 2,
    textAlign: 'center',
    maxWidth: 180,
  },
  pin: {
    width: 0,
    height: 0,
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderTopWidth: 12,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#fff',
    marginTop: -2,
  },
  footer: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: 'transparent',
  },
  footerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#023c69',
    marginBottom: 4,
  },
  footerText: {
    fontSize: 15,
    color: '#666',
    fontStyle: 'italic',
  },
  addressPill: {
    backgroundColor: '#e0eafc',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginHorizontal: 2,
    marginBottom: 4,
    minHeight: 28,
  },
  addressPillActive: {
    backgroundColor: '#023c69',
  },
  addressPillText: {
    color: '#023c69',
    fontWeight: 'bold',
    fontSize: 15,
  },
  addressPillTextActive: {
    color: '#fff',
  },
}); 